# Generated by Django 3.2.8 on 2021-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('DEL', 'DELUXE'), ('QU', 'QUEEN'), ('NAC', 'NON AC'), ('WAC', 'AC'), ('KIN', 'KING')], max_length=3),
        ),
    ]
