# Generated by Django 3.2.8 on 2021-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211219_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('NAC', 'NON AC'), ('WAC', 'AC'), ('QU', 'QUEEN'), ('KIN', 'KING'), ('DEL', 'DELUXE')], max_length=3),
        ),
    ]
